### ISSUE TITLE
ebi writing and reading sram problem.

### ISSUE THREAD

**Issue by shownb** [OpenNuvoton/MA35D1_linux-5.10.y#3]
Hello, I used ebi to read and write an IS62WV51216ALL. I followed the code in MA35D1_Linux_Applications/examples/ebi/ebi.c for reading and writing, but I found that the written content and the read content are not consistent. 

Then I used the following code (NUC980_Linux_Applications/demos/ebi
/ebi.c for) reading and writing, and found that the written and read content are consistent now.
```c
	printf("Start to Read/Write test\n");
	char tmp;
	for(i=0; i<uEbiSize; i++) {
		*(char *)(pEbiBuffer+i)=(char)i;
		tmp=*(char *)(pEbiBuffer+i);
		if(tmp!=(char)i) {
			printf("Read/Write test failed, patterns=0x%08x, data[%d]=0x%08x\n",(char)i,i,*(char*)(pEbiBuffer+i));
			return 0;
		}
	}
```
However, strangely enough, if I use the following code, I still encounter the same issue.
```C
	char tmp;
	int ok = 85;
	for(i=0; i<uEbiSize; i++) {
		*(char *)(pEbiBuffer+i)=(char)ok;
		tmp=*(char *)(pEbiBuffer+i);
		if(tmp!=(char)ok) {
			printf("Read/Write test failed, patterns=0x%08x, data[%d]=0x%08x\n",(char)ok,i,*(char*)(pEbiBuffer+i));
			return 0;
		}
	}
```
Read/Write test failed, patterns=0x00000055, data[0]=0x00000054

How can I solve this problem?

**Comment by ychuang3** [comment]
The EBI data width is 16-bits.
Please use *(unsigned short *) instead of *(char *)

As you post the same question in two different repository, please close one of them. 
Thank you.

**Comment by shownb** [comment]
I will close this one
